### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146

### ISSUE THREAD

**Issue by petertindemans** [flipboxfactory/craft-hubspot#2]
First of all, great work!

A error show up when opening the visitors page.

Error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_website.hubspot_visitors' doesn't exist
The SQL being executed was: SELECT *
FROM `hubspot_visitors`

Steps to reproduce:
1. New clean install of CraftCMS (3.3.17)
2. Installed the plugin with composer
3. Click "Visitors" > Error shows up
4. Reinstalled the plugin, no result

There is no table "hubspot_visitors" created after installing the plugin, "hubspot_connections" and "hubspot_objects" does exist.

**Comment by nateiler** [comment]
Confirmed. Good catch.

I'll get that added to the migration and patched up.

**Comment by nateiler** [comment]
Release https://github.com/flipboxfactory/craft-hubspot/releases/tag/1.2.2 should address the issue.

**Comment by petertindemans** [comment]
Solved by reinstalling 1.2.2, Thanks Nate!
